config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/chat_rooms_user" => "chat_rooms#rooms_user"
  resources :chat_rooms
  mount ActionCable.server => '/cable'
  root 'chat_rooms#index'
  get "/users/show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}
  after_create_commit { MessageBroadcastJob.perform_later self }

  def timestamp
    created_at.strftime('%d/%m/%Y ás %H:%M:%S')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :set_chat_room, only: [:edit, :update, :destroy]
  #@todo mostrar total de msgs da sala no badge e qual foi o horário da ultima msg enviada

  def index
  end

  def rooms_user
    @chat_rooms = ChatRoom.where(user_id: current_user.id)
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Sala de chat adicionada!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def update
    if @chat_room.update(chat_room_params)
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_user_path
    else
      render :edit
    end
  end

  def edit
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  def destroy
    @chat_room.destroy
    flash[:notice] = 'A sala foi excluída'
    redirect_to chat_rooms_user_path
  end


  private

  def set_chat_room
    @chat_room = ChatRoom.find(params[:id])
  end

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat_rooms/_form.html.erb
<div class="panel">
  <div class="card">
    <div class="card-block">
      <h4 class="card-title">Nova sala</h4>
      <img class="card-img-top img-fluid" src="/bot_perfil.png">
      <p class="card-text">
        <%= form_for @chat_room do |f| %>
        <div class="form-group">
          <%= f.label :Nome_da_sala %>
          <%= f.text_field :title, autofocus: true, class: 'form-control input' %>
        </div>
        <% if texto.start_with?("A") %>
          <%= link_to "<< Voltar", chat_rooms_user_path, class: "btn btn-primary" %>
        <% end %>
        <%= f.submit "#{texto}", class: 'btn btn-primary' %>
      <% end %>
      </p>
    </div>
  </div>
</div>

app/views/chat_rooms/edit.html.erb
<%= render "form", texto: "Atualizar!" %>

app/views/chat_rooms/index.html.erb
<!--<h1>Chat rooms</h1>-->
<!--<ul>-->
<%#= render @chat_rooms %>
<!--</ul>-->
<!--<p class="lead"><%#= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>-->

app/views/chat_rooms/new.html.erb
<%= render "form", texto: "Criar" %>

app/views/chat_rooms/rooms_user.html.erb
<div class="panel">
  <div class="card">
    <div class="card-block">
      <h4 class="card-title">Suas salas</h4>
      <p class="card-text">
        <% for sala in @chat_rooms %>
        <div class="list_card">
          <%= link_to "#{sala.title}", edit_chat_room_path(sala), class: "pull-left" %> <%= link_to 'X',sala, method: :delete, data: {confirm: "Você tem certeza que deseja excluir a sala #{sala.title}?"}, :class => 'pull-right' %> <br>
        </div>
      <% end %>

      </p>
      <div class="obs">
        Clique no nome da sala para editar ou click em X para excluí-la.
      </div>
    </div>
  </div>
</div>

app/views/chat_rooms/show.html.erb
<h5 class="nome_sala">Você está na Sala: <strong><%= @chat_room.title.capitalize %></strong></h5>

<div id="messages" data-chat-room-id="<%= @chat_room.id %>" class="chat_area">
  <%= render @chat_room.messages %>
</div>

<%= form_for @message, url: '#' do |f| %>
  <div class="form-group">
    <%= f.label :Escreva_a_mensagem %>
    <%= f.text_area :body, class: 'form-control' %>
    <small class="text-muted">Insira de 2 a 1000 carateres</small>
  </div>
  <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
  <%= f.submit "Enviar!", class: 'btn btn-primary' %>
<% end %>

<script>
    $(document).ready(function () {
        var objDiv = document.getElementsByClassName("chat_area")[0];
        objDiv.scrollTop = objDiv.scrollHeight;
    });
</script>

app/views/layouts/_appdevise.html.erb
<%= render "layouts/head_meta_application" %>
<body>
<div id="wrapper">
  <div class="site-wrapper">
    <% if user_signed_in? %>
      <%= render "shared/sidebar" %>
    <% end %>
    <div id="page-content-wrapper col-md-1">
      <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
        <span class="hamb-top"></span>
        <span class="hamb-middle"></span>
        <span class="hamb-bottom"></span>
      </button>
     <%= render "layouts/navbar" %>

      <div class="col-md-12 message_section">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render "layouts/js" %>
</body>
</html>

app/views/layouts/_head_meta_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat8bits</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= render "shared/meta" %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_js.html.erb
<script>
    $(document).ready(function () {
        var trigger = $('.hamburger'),
            isClosed = false;

        var first_username = $('.username')[0];
        console.log(first_username);

        trigger.click(function () {
            hamburger_cross();
        });

        function hamburger_cross() {

            if (isClosed == true) {
                trigger.removeClass('is-open');
                trigger.addClass('is-closed');
                isClosed = false;
            } else {
                trigger.removeClass('is-closed');
                trigger.addClass('is-open');
                isClosed = true;
            }
        }

        $('[data-toggle="offcanvas"]').click(function () {
            $('#wrapper').toggleClass('toggled');
        });
    });
</script>

app/views/layouts/_navbar.html.erb
<nav class="new_message_head col-md-11">
  <div class="pull-left username">
    <strong>Nick: </strong><%= link_to "#{current_user.name}", edit_user_registration_path %>
  </div>
  <div class="pull-right links_menu">
    <%= link_to "", "/chat_rooms_user", class: "icon fa fa-cog" %>
    <%= link_to "", destroy_user_session_path, method: :delete, data: {confirm: 'Você tem certeza que deseja sair?'}, class: "icon fa fa-power-off" %>
  </div>
</nav>

app/views/layouts/application.html.erb
<%= render "layouts/head_meta_application" %>
<body>
<div id="wrapper">
  <div class="site-wrapper">
    <% if user_signed_in? %>
      <%= render "shared/sidebar" %>
    <% end %>
    <div id="page-content-wrapper col-md-1">
      <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
        <span class="hamb-top"></span>
        <span class="hamb-middle"></span>
        <span class="hamb-bottom"></span>
      </button>
      <%= render "layouts/navbar" %>

      <div class="col-md-12 message_section">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render "layouts/js" %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat8bits</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/messages/_message.html.erb
  <ul class="list-unstyled">
    <li class="left clearfix">
                     <span class="chat-img1 pull-left">
                     <img src="/spaceinvader.png" alt="User Avatar" width="60px" height="60px">
                     </span>

      <div class="chat-body1 clearfix">
        <p>
          <strong><%= message.user.name %></strong> <%= message.timestamp %><br>
          <%= message.body %></p>
        <!--      <div class="chat_time pull-right"></div>-->
      </div>
    </li>
  </ul>

app/views/shared/_meta.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=yes">

app/views/shared/_sidebar.html.erb
<% @salas = ChatRoom.all %>
<nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
  <div class="row">
    <div class="custom-search-input">
      <strong>Salas de chat disponíveis</strong>
    </div>
    <div class="all_conversation">
      <div class="input-group" id="search">
        <center><input type="text" class="search-query form-control" placeholder="Insira o nome da sala"/></center>
      </div>
    </div>
    <div class="member_list">
      <ul class="list-unstyled">
        <% @salas.each do |sala| %>
          <a href="/chat_rooms/<%= sala.id %>">
            <li class="left clearfix salas">
                          <span class="chat-img pull-left">
                       <img src="/android_terminal.png" alt="User Avatar" class="img-circle" width="47px" height="45px">
                       </span>
              <div class="chat-body clearfix">
                <div class="header_sec">
                  <strong class="primary-font"><%= sala.title.capitalize %></strong>
                  <!--                    <strong class="pull-right"><span class="badge">3</span>09:45AM</strong>-->
                </div>
              </div>
            </li>
          </a>
        <% end %>
      </ul>
      <p class="lead"><%= link_to 'Nova sala', new_chat_room_path, class: 'btn btn-primary' %></p>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<div class="panel">
  <div class="card">
    <div class="card-block">
      <h4 class="card-title">Seu perfil</h4>
      <img class="card-img-top img-fluid" src="/bot_perfil.png">
      <p class="card-text">
      <div class="obs" style="text-align: justify !important;">
        <strong>Nick:</strong><%= current_user.name %><br>
        <strong>E-mail:</strong><%= current_user.email %>
      </div>
      <%= link_to "Editar Perfil",edit_user_registration_path, class:"btn btn-primary" %>
      </p>
    </div>
  </div>
</div>